dist: xenial
language: cpp
compiler: gcc
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
 - cd Source/PlusIrbis
 - cmake .
 - make
