version: 1.0.{build}
configuration: Debug
platform: x64
image: Visual Studio 2017

build:
  project: PlusIrbis.2017.sln

after_build:
  - cmd: utils\doxygen

artifacts:
  - path: doxygen\html
    name: HtmlDocs
