version: 1.0.{build}
configuration:
  - Debug
  - DebugDll
  - Release
  - ReleaseDll
platform: x64
image: Visual Studio 2017

before_build:
- cmd: choco install doxygen.portable

build:
  project: Source\PlusIrbis.sln

after_build:
- cmd: doxygen

artifacts:
  - path: Source\x64
    name: Binaries
