version: 1.0.{build}
configuration:
  - Debug
  - DebugDll
  - Release
  - ReleaseDll
platform: x64
image: Visual Studio 2017

build:
  project: Source\PlusIrbis.sln

artifacts:
  - path: Source\x64
    name: Binaries
