version: 1.0.{build}
configuration:
  - Debug
  - DebugDll
  - Release
  - ReleaseDll
  - ReleaseStatic
platform: x64
image: Visual Studio 2017

build:
  project: Source\PlusIrbis.2017.sln

after_build:
- cmd: Utils\doxygen

artifacts:
  - path: Source\x64
    name: Binaries
  - path: doxygen\html
    name: HtmlDocs
