name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: source ./build.sh
    - name: tests
      run: ./artifacts/safeTests
    - uses: actions/upload-artifact@v1
      with:
        name: treasure
        path: artifacts
